# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='balance_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
