# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_balance', '0002_auto_20171008_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
