# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_balance', '0003_auto_20171008_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 18, 11, 42, 86287)),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Savings', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.CharField(default='Jasper', max_length=50),
        ),
    ]
