# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
